name: Research
channels:
  - defaults
dependencies:
  - joblib=0.13.2
  - keras=2.2.4
  - matplotlib=3.0.2
  - natsort=6.0.0
  - pandas=0.24.2
  - python=3.6.7
  - pytables=3.5.2
  - scikit-image-0.15.0
  - scikit-learn=0.20.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - pip:
    - git+https://github.com/RomainCendre/keras-vis.git#egg=keras-vis
    - git+https://github.com/luispedro/mahotas.git#egg=mahotas
    - git+https://github.com/garydoranjr/misvm.git#egg=misvm
    - markups==3.0.0
    - pillow==5.3.0
    - pyocr==0.5.3
    - pypdf2==1.26.0
    - pytesseract==0.2.4
    - pywavelets==1.0.1
    - scikit-image==0.14.1
    - textile==3.0.3
