#!/bin/ksh

# La file d'attente 3d : NE PAS CHANGER
#$ -q 3d@webern07.u-bourgogne.fr

# L'adresse electronique de contact
#$ -M romain.cendre@gmail.com

# Le nom du fichier de sortie 
#$ -o deep.out

# Le nom du job
#$ -N deep

# Lancement du calcul
export PYTHONPATH=/work/le2i/rc621381/classification
export XDG_RUNTIME_DIR=/work/le2i/rc621381/XDG
~/envs/GPU/bin/python /work/le2i/rc621381/classification/manuscript/dermatology/microscopy/a_deep.py
