name: Research
channels:
  - defaults
dependencies:
  - matplotlib
  - natsort
  - pandas
  - python=3.6.7
  - scikit-image
  - scikit-learn
  - tensorflow=2.0.0
  - pip:
    - git+https://github.com/RomainCendre/keras-vis.git#egg=keras-vis
    - git+https://github.com/luispedro/mahotas.git#egg=mahotas
    - git+https://github.com/RomainCendre/misvm.git#egg=misvm
    - imbalanced-learn
    - jinja2
    - jupyter_contrib_nbextensions
    - markups
    - pillow
    - imbalanced-learn
    - pyocr
    - pypdf2
    - pytesseract
    - pywavele
